### ISSUE TITLE
General Documentation Question

### ISSUE THREAD

**Issue by umaqs** [enginkirmaci/Imaging-Library#1]
Hello,

I am amazed by your work. Just a couple of questions I have regarding the document scanning:

Does this library support perspective transformation (if picture is taken from different angles)?
What is effect of different ObjectOrder values in BlobCounter:
 ```
var blobCounter = new BlobCounter
{
    ObjectsOrder = ObjectsOrder.Size // or XY, YX, Area ?
};
```

**Comment by enginkirmaci** [comment]
Hello @Unitarian,

Yes, library supports perspective transformation. After suitable blob found, it uses quadrilateral transformation to correct image. 

For blob processing, I used AForge.net code for it. You can check it from here. http://www.aforgenet.com/framework/features/blobs_processing.html

As I understand from ObjectsOrder, size calculates lines length, area is what it is. I don't know XY or YX. For detection, I found best option is ObjectsOrder.Size, which results of testing different scans.
